// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectWithLibFixed.Model.Sample;

namespace ProjectWithLibFixed.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20190427234954_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:Sequence:sample.message_id_seq", "'message_id_seq', 'sample', '1', '1', '', '', 'Int32', 'False'");

            modelBuilder.Entity("ProjectWithLibFixed.Model.Sample.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('sample.message_id_seq'::regclass)");

                    b.Property<string>("Message1")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.ToTable("message","sample");
                });
#pragma warning restore 612, 618
        }
    }
}
